/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.somi92.seecsk.gui.panels;

import com.github.somi92.seecsk.data.Sesija;
import com.github.somi92.seecsk.domain.Grupa;
import com.github.somi92.seecsk.domain.Prisustvo;
import com.github.somi92.seecsk.domain.Trening;
import com.github.somi92.seecsk.gui.FNewTraining;
import com.github.somi92.seecsk.model.tables.trening.PrisustvaTableEditor;
import com.github.somi92.seecsk.model.tables.trening.PrisustvaTableModel;
import com.github.somi92.seecsk.model.tables.trening.PrisustvaTableRenderer;
import com.github.somi92.seecsk.model.tables.trening.TreningTableModel;
import com.github.somi92.seecsk.server.ServerInstance;
import com.github.somi92.seecsk.transfer.OdgovorObjekat;
import com.github.somi92.seecsk.transfer.ZahtevObjekat;
import com.github.somi92.seecsk.util.Ref;
import com.github.somi92.seecsk.util.SistemskeOperacije;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author milos
 */
public class TrainingPanel extends javax.swing.JPanel {

    /**
     * Creates new form CategoriesGroupsPanel
     */
    public TrainingPanel() {
        initializeTrainingPanel();
    }
    
    public void initializeTrainingPanel() {
        initComponents();
        initForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpnlTraining = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblTraining = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblAttendance = new javax.swing.JTable();
        jbtnNoviTrening = new javax.swing.JButton();
        jbtnIzmeniTrening = new javax.swing.JButton();
        jbtnObrisiTrening = new javax.swing.JButton();
        jbtnSacuvajPrisustva = new javax.swing.JButton();
        jcmbGroups = new javax.swing.JComboBox();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Evidencija treninga");

        jpnlTraining.setBorder(null);

        jLabel2.setText("Grupe:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci za izabranu grupu"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Treninzi za izabranu grupu"));

        jtblTraining.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblTraining);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Prisustva za izabrani trening"));

        jtblAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtblAttendance);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnNoviTrening.setText("Dodaj trening");
        jbtnNoviTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNoviTreningActionPerformed(evt);
            }
        });

        jbtnIzmeniTrening.setText("Detalji treninga");
        jbtnIzmeniTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniTreningActionPerformed(evt);
            }
        });

        jbtnObrisiTrening.setText("Obriši trening");
        jbtnObrisiTrening.setToolTipText("");
        jbtnObrisiTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiTreningActionPerformed(evt);
            }
        });

        jbtnSacuvajPrisustva.setText("Sačuvaj izmene");
        jbtnSacuvajPrisustva.setEnabled(false);
        jbtnSacuvajPrisustva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajPrisustvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtnNoviTrening, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnIzmeniTrening, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnObrisiTrening, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnSacuvajPrisustva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jbtnNoviTrening, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnIzmeniTrening, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnObrisiTrening, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jbtnSacuvajPrisustva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jcmbGroups.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmbGroups.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbGroupsItemStateChanged(evt);
            }
        });
        jcmbGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbGroupsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlTrainingLayout = new javax.swing.GroupLayout(jpnlTraining);
        jpnlTraining.setLayout(jpnlTrainingLayout);
        jpnlTrainingLayout.setHorizontalGroup(
            jpnlTrainingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlTrainingLayout.createSequentialGroup()
                .addGroup(jpnlTrainingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlTrainingLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jcmbGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlTrainingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnlTrainingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpnlTrainingLayout.setVerticalGroup(
            jpnlTrainingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlTrainingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcmbGroups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnlTraining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlTraining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIzmeniTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniTreningActionPerformed
        int row = jtblTraining.getSelectedRow();
        if(row == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite trening iz tabele treninga.");
        } else {
            Sesija.vratiInstancu().vratiMapuSesije().put(Sesija.GRUPA, (Grupa) jcmbGroups.getSelectedItem());
            Sesija.vratiInstancu().vratiMapuSesije().put(Sesija.TRENING, ttm.vratiTreningeTabele().get(row));
            new FNewTraining(null, true).setVisible(true);
            setTrainig();
        }
    }//GEN-LAST:event_jbtnIzmeniTreningActionPerformed

    private void jcmbGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbGroupsActionPerformed
        setTrainig();
        if(ptm != null) {
            ptm.postaviPrisustvaTabele(new ArrayList<>());
        }
    }//GEN-LAST:event_jcmbGroupsActionPerformed

    private void jcmbGroupsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbGroupsItemStateChanged

    }//GEN-LAST:event_jcmbGroupsItemStateChanged

    private void jbtnNoviTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNoviTreningActionPerformed
        Sesija.vratiInstancu().vratiMapuSesije().put(Sesija.GRUPA, (Grupa) jcmbGroups.getSelectedItem());
        new FNewTraining(null, true).setVisible(true);
        ptm.postaviPrisustvaTabele(new ArrayList<>());
        setTrainig();
    }//GEN-LAST:event_jbtnNoviTreningActionPerformed

    private void jbtnObrisiTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiTreningActionPerformed
        int row = jtblTraining.getSelectedRow();
        if(row == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite trening iz tabele treninga.");
        } else {
            int response = JOptionPane.showConfirmDialog(this, "Jeste li sigurni da želite izbrisati izabranog člana?",
                "Potvrdite izbor", JOptionPane.OK_CANCEL_OPTION);
            if(response == JOptionPane.OK_OPTION) {
                
                ZahtevObjekat zo = new ZahtevObjekat();
                zo.setSistemskaOperacija(SistemskeOperacije.SO_OBRISI_TRENING);
                zo.setParametar(ttm.vratiTreningeTabele().get(row));
                ServerInstance.vratiInstancu().posaljiZahtev(zo);
                OdgovorObjekat oo = ServerInstance.vratiInstancu().vratiOdgovor();
                boolean res = oo.getStatusOperacije()==0;
//                boolean res = KontrolerPL.obrisiTrening(ttm.vratiTreningeTabele().get(row));
                if(res) {
                    setTrainig();
                    ptm.postaviPrisustvaTabele(new ArrayList<>());
                }
            }
        }
    }//GEN-LAST:event_jbtnObrisiTreningActionPerformed

    private void jbtnSacuvajPrisustvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajPrisustvaActionPerformed
        jbtnSacuvajPrisustva.setEnabled(false);
        int trainingRow = jtblTraining.getSelectedRow();
        if(trainingRow == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati trening.");
            return;
        }
        Trening trening = ttm.vratiTreningeTabele().get(trainingRow);
        List<Prisustvo> prisustva = ptm.vratiPrisustvaTabele();
        trening.setPrisustva(prisustva);
        
        ZahtevObjekat zo = new ZahtevObjekat();
        zo.setSistemskaOperacija(SistemskeOperacije.SO_ZAPAMTI_TRENING);
        zo.setParametar(trening);
        ServerInstance.vratiInstancu().posaljiZahtev(zo);
        OdgovorObjekat oo = ServerInstance.vratiInstancu().vratiOdgovor();
        if(oo.getStatusOperacije()==0) {
            JOptionPane.showMessageDialog(this, "Trening je uspešno sačuvan.");
        } else {
            JOptionPane.showMessageDialog(this, "Greška! Trening nije uspešno sačuvan!");
        }
//        KontrolerPL.sacuvajIliAzurirajTrening(trening);
    }//GEN-LAST:event_jbtnSacuvajPrisustvaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnIzmeniTrening;
    private javax.swing.JButton jbtnNoviTrening;
    private javax.swing.JButton jbtnObrisiTrening;
    private javax.swing.JButton jbtnSacuvajPrisustva;
    private javax.swing.JComboBox jcmbGroups;
    private javax.swing.JPanel jpnlTraining;
    private javax.swing.JTable jtblAttendance;
    private javax.swing.JTable jtblTraining;
    // End of variables declaration//GEN-END:variables
    private TreningTableModel ttm;
    private PrisustvaTableModel ptm;
    private boolean prisustvaPromenjena;
    
    private void initForm() {
        prisustvaPromenjena = false;
        Ref<List<Grupa>> refGrupe = new Ref(new ArrayList<>());
        
        ZahtevObjekat zo = new ZahtevObjekat();
        zo.setSistemskaOperacija(SistemskeOperacije.SO_VRATI_LISTU_GRUPA);
        zo.setUcitajListe(true);
        zo.setParametar(refGrupe);
        ServerInstance.vratiInstancu().posaljiZahtev(zo);
        OdgovorObjekat oo = ServerInstance.vratiInstancu().vratiOdgovor();
        refGrupe = oo.getPodaci();
//        KontrolerPL.vratiListuGrupa(refGrupe, true);
        jcmbGroups.removeAllItems();
        for(Grupa g : refGrupe.get()) {
            jcmbGroups.addItem(g);
        }
        
//        setTrainig();
        jtblTraining.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                setAttendance();
            }
        });
        
        jtblAttendance.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                int column = jtblAttendance.getSelectedColumn();
                if(column == 1 || column == 2) {
                    jbtnSacuvajPrisustva.setEnabled(true);
                }
            }
        });
        
        ptm = new PrisustvaTableModel();
        jtblAttendance.setModel(ptm);
        
        TableColumnModel tcm = jtblAttendance.getColumnModel();
        TableColumn tc = tcm.getColumn(1);
        
        PrisustvaTableRenderer ptr = new PrisustvaTableRenderer();
        ptr.setHorizontalAlignment(SwingConstants.TRAILING);
        tc.setCellRenderer(ptr);
        tc.setCellEditor(new PrisustvaTableEditor());
        
        TableColumn tc1 = tcm.getColumn(2);
        DefaultTableCellRenderer rnd = new DefaultTableCellRenderer();
        rnd.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        tc1.setCellRenderer(rnd);
        tc1.setCellEditor(new DefaultCellEditor(new JTextField()));
    }
    
    public void setTrainig() {
        Grupa selected = (Grupa) jcmbGroups.getSelectedItem();
        if(selected == null) {
            return;
        }
        List<Trening> treninzi = new ArrayList<>();
        Trening temp = new Trening();
        temp.setGrupa(selected);
        treninzi.add(temp);
        Ref<List<Trening>> refTreninzi = new Ref(treninzi);
        List<String> kriterijumPretrage = new ArrayList<>();
        kriterijumPretrage.add("grupa");
        
        ZahtevObjekat zo = new ZahtevObjekat();
        zo.setSistemskaOperacija(SistemskeOperacije.SO_PRONADJI_TRENINGE);
        zo.setKriterijumPretrage(kriterijumPretrage);
        zo.setParametar(refTreninzi);
        ServerInstance.vratiInstancu().posaljiZahtev(zo);
        OdgovorObjekat oo = ServerInstance.vratiInstancu().vratiOdgovor();
        refTreninzi = oo.getPodaci();
//        KontrolerPL.vratiTreninge(refTreninzi, kriterijumPretrage);
        treninzi = refTreninzi.get();
        ttm = new TreningTableModel(treninzi);
        jtblTraining.setModel(ttm);
    }
    
    private void setAttendance() {
        int selectedRow = jtblTraining.getSelectedRow();
        if(selectedRow > -1) {
            Trening t = ttm.vratiTreningeTabele().get(selectedRow);
            Ref<Trening> treningRef = new Ref(t);
            
            ZahtevObjekat zo = new ZahtevObjekat();
            zo.setSistemskaOperacija(SistemskeOperacije.SO_UCITAJ_TRENING);
            zo.setParametar(treningRef);
            ServerInstance.vratiInstancu().posaljiZahtev(zo);
            OdgovorObjekat oo = ServerInstance.vratiInstancu().vratiOdgovor();
            treningRef = oo.getPodaci();
//            KontrolerPL.ucitajTrening(treningRef);
            ptm.postaviPrisustvaTabele(new ArrayList<>());
            ptm.postaviPrisustvaTabele(treningRef.get().getPrisustva());
        }
    }
    
    public void setGroup(Grupa g) {
        jcmbGroups.setSelectedItem(g);
//        setTrainig();
    }
}
