/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.somi92.seecsk.gui;

import com.github.somi92.seecsk.gui.panels.TrainingPanel;
import com.github.somi92.seecsk.gui.panels.MembersPanel;
import com.github.somi92.seecsk.gui.panels.MembershipFeePanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author milos
 */
public class FMainForm extends javax.swing.JFrame {

    /**
     * Creates new form FMainForm
     */
    public FMainForm() {
        initComponents();
        initPanels();
        initToolbar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlMainPanel = new javax.swing.JPanel();
        jpnlToolbar = new javax.swing.JPanel();
        jbtnMembers = new javax.swing.JButton();
        jbtnTraining = new javax.swing.JButton();
        jbtnMembershipFee = new javax.swing.JButton();
        jpnlStatus = new javax.swing.JPanel();
        jlblStatus = new javax.swing.JLabel();
        jmnuMenuBar = new javax.swing.JMenuBar();
        jmnuMain = new javax.swing.JMenu();
        jmnuiMembers = new javax.swing.JMenuItem();
        jmnuiTraining = new javax.swing.JMenuItem();
        jmnuiFee = new javax.swing.JMenuItem();
        jmnuApp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEECSK - Sistem za elektronsku evidenciju članova sportskog kluba");
        setResizable(false);

        jpnlMainPanel.setLayout(new java.awt.CardLayout());

        jpnlToolbar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbtnMembers.setBackground(new java.awt.Color(204, 204, 204));
        jbtnMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/somi92/seecsk/resources/members.png"))); // NOI18N
        jbtnMembers.setToolTipText("Članovi kluba");
        jbtnMembers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMembersActionPerformed(evt);
            }
        });

        jbtnTraining.setBackground(new java.awt.Color(204, 204, 204));
        jbtnTraining.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/somi92/seecsk/resources/groups.png"))); // NOI18N
        jbtnTraining.setToolTipText("Kategorije, grupe i treninzi");
        jbtnTraining.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTrainingActionPerformed(evt);
            }
        });

        jbtnMembershipFee.setBackground(new java.awt.Color(204, 204, 204));
        jbtnMembershipFee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/somi92/seecsk/resources/finance.png"))); // NOI18N
        jbtnMembershipFee.setToolTipText("Članarine");
        jbtnMembershipFee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnMembershipFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMembershipFeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlToolbarLayout = new javax.swing.GroupLayout(jpnlToolbar);
        jpnlToolbar.setLayout(jpnlToolbarLayout);
        jpnlToolbarLayout.setHorizontalGroup(
            jpnlToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlToolbarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jbtnMembers)
                .addGap(18, 18, 18)
                .addComponent(jbtnTraining)
                .addGap(18, 18, 18)
                .addComponent(jbtnMembershipFee)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlToolbarLayout.setVerticalGroup(
            jpnlToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnTraining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnMembershipFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpnlStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jlblStatus.setText("Status:");

        javax.swing.GroupLayout jpnlStatusLayout = new javax.swing.GroupLayout(jpnlStatus);
        jpnlStatus.setLayout(jpnlStatusLayout);
        jpnlStatusLayout.setHorizontalGroup(
            jpnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnlStatusLayout.setVerticalGroup(
            jpnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        jmnuMain.setText("Glavni meni");

        jmnuiMembers.setText("Evidencija članova");
        jmnuiMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuiMembersActionPerformed(evt);
            }
        });
        jmnuMain.add(jmnuiMembers);

        jmnuiTraining.setText("Evidencija treninga");
        jmnuiTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuiTrainingActionPerformed(evt);
            }
        });
        jmnuMain.add(jmnuiTraining);

        jmnuiFee.setText("Evidencija članarina");
        jmnuiFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuiFeeActionPerformed(evt);
            }
        });
        jmnuMain.add(jmnuiFee);

        jmnuMenuBar.add(jmnuMain);

        jmnuApp.setText("Aplikacija");
        jmnuMenuBar.add(jmnuApp);

        setJMenuBar(jmnuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnlStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnlMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnlMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpnlStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnuiMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuiMembersActionPerformed
        CardLayout cl = (CardLayout) jpnlMainPanel.getLayout();
        cl.show(jpnlMainPanel, "panel1");
//        panel1.initializeMembersPanel();
        panel1.azurirajTabelu();
    }//GEN-LAST:event_jmnuiMembersActionPerformed

    private void jmnuiTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuiTrainingActionPerformed
        CardLayout cl = (CardLayout) jpnlMainPanel.getLayout();
        cl.show(jpnlMainPanel, "panel2");
//        panel2.initializeTrainingPanel();
        panel2.setTrainig();
    }//GEN-LAST:event_jmnuiTrainingActionPerformed

    private void jbtnMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMembersActionPerformed
        CardLayout cl = (CardLayout) jpnlMainPanel.getLayout();
        cl.show(jpnlMainPanel, "panel1");
//        panel1.initializeMembersPanel();
        panel1.azurirajTabelu();
    }//GEN-LAST:event_jbtnMembersActionPerformed

    private void jbtnTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTrainingActionPerformed
        CardLayout cl = (CardLayout) jpnlMainPanel.getLayout();
        cl.show(jpnlMainPanel, "panel2");
//        panel2.initializeTrainingPanel();
        panel2.setTrainig();
    }//GEN-LAST:event_jbtnTrainingActionPerformed

    private void jbtnMembershipFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMembershipFeeActionPerformed
        CardLayout cl = (CardLayout) jpnlMainPanel.getLayout();
        cl.show(jpnlMainPanel, "panel3");
        panel3.initForm();
    }//GEN-LAST:event_jbtnMembershipFeeActionPerformed

    private void jmnuiFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuiFeeActionPerformed
        CardLayout cl = (CardLayout) jpnlMainPanel.getLayout();
        cl.show(jpnlMainPanel, "panel3");
        panel3.initForm();
    }//GEN-LAST:event_jmnuiFeeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnMembers;
    private javax.swing.JButton jbtnMembershipFee;
    private javax.swing.JButton jbtnTraining;
    private javax.swing.JLabel jlblStatus;
    private javax.swing.JMenu jmnuApp;
    private javax.swing.JMenu jmnuMain;
    private javax.swing.JMenuBar jmnuMenuBar;
    private javax.swing.JMenuItem jmnuiFee;
    private javax.swing.JMenuItem jmnuiMembers;
    private javax.swing.JMenuItem jmnuiTraining;
    private javax.swing.JPanel jpnlMainPanel;
    private javax.swing.JPanel jpnlStatus;
    private javax.swing.JPanel jpnlToolbar;
    // End of variables declaration//GEN-END:variables
    private static MembersPanel panel1;
    private static TrainingPanel panel2;
    private static MembershipFeePanel panel3;
    
    private void initPanels() {
        panel1 = new MembersPanel(this);
        panel2 = new TrainingPanel(this);
        panel3 = new MembershipFeePanel(this);
        jpnlMainPanel.add("panel1", panel1);
        jpnlMainPanel.add("panel2", panel2);
        jpnlMainPanel.add("panel3", panel3);
    }

    private void initToolbar() {
        
    }
    
    public static TrainingPanel getTrainingPanel() {
        return panel2;
    }
    
    public void setStatus(String status) {
        jlblStatus.setText("Status: "+status);
    }
}
