/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.somi92.seecsk.gui;

import com.github.somi92.seecsk.server.ServerInstance;
import com.github.somi92.seecskcommon.domain.Grupa;
import com.github.somi92.seecskcommon.domain.Kategorija;
import com.github.somi92.seecskcommon.transfer.OdgovorObjekat;
import com.github.somi92.seecskcommon.transfer.ZahtevObjekat;
import com.github.somi92.seecskcommon.util.Ref;
import com.github.somi92.seecskcommon.util.SistemskeOperacije;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author milos
 */
public class FNewGroup extends javax.swing.JDialog {

    private Grupa grupa;
    
    /**
     * Creates new form FNewGroup
     */
    public FNewGroup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtNapomena = new javax.swing.JTextArea();
        jcmbKategorija = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jbtnZapamti = new javax.swing.JButton();
        jbtnKreirajGrupu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj novu grupu");

        jLabel1.setText("Naziv:");

        jtxtNaziv.setEnabled(false);

        jLabel2.setText("Napomena:");

        jtxtNapomena.setColumns(20);
        jtxtNapomena.setLineWrap(true);
        jtxtNapomena.setRows(5);
        jtxtNapomena.setWrapStyleWord(true);
        jtxtNapomena.setEnabled(false);
        jScrollPane1.setViewportView(jtxtNapomena);

        jcmbKategorija.setEnabled(false);

        jLabel3.setText("Kategorija:");

        jbtnZapamti.setText("Zapamti");
        jbtnZapamti.setEnabled(false);
        jbtnZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZapamtiActionPerformed(evt);
            }
        });

        jbtnKreirajGrupu.setText("Kreiraj grupu");
        jbtnKreirajGrupu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKreirajGrupuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnKreirajGrupu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnZapamti, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtNaziv)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(jcmbKategorija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnZapamti, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnKreirajGrupu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZapamtiActionPerformed
        String naziv = jtxtNaziv.getText().trim();
        String napomena = jtxtNapomena.getText().trim();
        Kategorija kategorija = (Kategorija) jcmbKategorija.getSelectedItem();
        if(naziv == null || naziv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti naziv grupe.");
            return;
        }
        grupa.setNaziv(naziv);
        grupa.setNapomena(napomena);
        grupa.setKategorija(kategorija);
        
        ZahtevObjekat zo = new ZahtevObjekat();
        zo.setSistemskaOperacija(SistemskeOperacije.SO_ZAPAMTI_GRUPU);
        zo.setParametar(grupa);
        ServerInstance.vratiInstancu().posaljiZahtev(zo);
        OdgovorObjekat oo = ServerInstance.vratiInstancu().vratiOdgovor();
        if(oo.getStatusOperacije() != 0) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti novu grupu.", "Greška", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem je uspešno zapamtio novu grupu.");
            dispose();
        }
    }//GEN-LAST:event_jbtnZapamtiActionPerformed

    private void jbtnKreirajGrupuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKreirajGrupuActionPerformed
        Ref<Grupa> refGrupa = new Ref<>(new Grupa());
        ZahtevObjekat zo = new ZahtevObjekat();
        zo.setSistemskaOperacija(SistemskeOperacije.SO_KREIRAJ_GRUPU);
        zo.setParametar(refGrupa);
        ServerInstance.vratiInstancu().posaljiZahtev(zo);
        OdgovorObjekat oo = ServerInstance.vratiInstancu().vratiOdgovor();
        if(oo.getStatusOperacije() != 0) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da kreira novu grupu.", "Greška", JOptionPane.ERROR_MESSAGE);
        } else {
            refGrupa = oo.getPodaci();
            grupa = refGrupa.get();
            jtxtNaziv.setEnabled(true);
            jtxtNapomena.setEnabled(true);
            jcmbKategorija.setEnabled(true);
            jbtnZapamti.setEnabled(true);
            jbtnKreirajGrupu.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Sistem je kreirao novu grupu.");
        }
    }//GEN-LAST:event_jbtnKreirajGrupuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnKreirajGrupu;
    private javax.swing.JButton jbtnZapamti;
    private javax.swing.JComboBox jcmbKategorija;
    private javax.swing.JTextArea jtxtNapomena;
    private javax.swing.JTextField jtxtNaziv;
    // End of variables declaration//GEN-END:variables

    private void initForm() {
        
        Ref<List<Kategorija>> kategorije = new Ref(new ArrayList<>());
        ZahtevObjekat zo = new ZahtevObjekat();
        zo.setSistemskaOperacija(SistemskeOperacije.SO_VRATI_LISTU_KATEGORIJA);
        zo.setParametar(kategorije);
        ServerInstance.vratiInstancu().posaljiZahtev(zo);
        OdgovorObjekat oo = ServerInstance.vratiInstancu().vratiOdgovor();
        kategorije = oo.getPodaci();
        if(oo.getStatusOperacije() != 0) {
            JOptionPane.showMessageDialog(this, "Greška! Sistem ne može da vrati listu kategorija.");
            dispose();
            return;
        } else {
            jcmbKategorija.removeAllItems();
            for(Kategorija k : kategorije.get()) {
                jcmbKategorija.addItem(k);
            }
        }
        
        // FIX: move this to create button, according to docs
//        Ref<Grupa> refGrupa = new Ref<>(new Grupa());
//        zo = new ZahtevObjekat();
//        zo.setSistemskaOperacija(SistemskeOperacije.SO_KREIRAJ_GRUPU);
//        zo.setParametar(refGrupa);
//        ServerInstance.vratiInstancu().posaljiZahtev(zo);
//        oo = ServerInstance.vratiInstancu().vratiOdgovor();
//        if(oo.getStatusOperacije() != 0) {
//            JOptionPane.showMessageDialog(this, "Greška! Sistem ne može da kreira grupu.");
//            dispose();
//            return;
//        } else {
//            refGrupa = oo.getPodaci();
//            grupa = refGrupa.get();
//        }
    }
}
